import QtQuick 2.1

ListModel{
    id:yibanModel
    ListElement{
        img:"qrc:/images/4.png"
        name:"寒山居士"
        space:"qrc:/images/callme.png"
        limit:"qrc:/images/callme.png"
        contents:"一叶知秋，一绿春来，一热夏至，一冷冬眠"
    }
    ListElement{
        img:"qrc:/images/1.png"
        name:"寒士"
        space:"qrc:/images/callme.png"
        limit:"qrc:/images/vip.png"
        contents:"一叶知秋，一绿春来，一热夏至，一冷冬眠"
    }
    ListElement{
        img:"qrc:/images/2.png"
        name:"寒山士"
        space:"qrc:/images/callme.png"
        limit:""
        contents:"一叶知秋，一绿春来，一热夏至，一冷冬眠"
    }
    ListElement{
        img:"qrc:/images/3.png"
        name:"山居士"
        space:"qrc:/images/callme.png"
        limit:"qrc:/images/vip.png"
        contents:"一叶知秋，一绿春来，一热夏至，一冷冬眠"
    }
    ListElement{
        img:"qrc:/images/4.png"
        name:"寒山居士"
        space:"qrc:/images/callme.png"
        limit:"qrc:/images/callme.png"
        contents:"一叶知秋，一绿春来，一热夏至，一冷冬眠"
    }
    ListElement{
        img:"qrc:/images/4.png"
        name:"寒山居士"
        space:"qrc:/images/callme.png"
        limit:"qrc:/images/callme.png"
        contents:"一叶知秋，一绿春来，一热夏至，一冷冬眠"
    }
    ListElement{
        img:"qrc:/images/4.png"
        name:"寒山居士"
        space:"qrc:/images/callme.png"
        limit:"qrc:/images/callme.png"
        contents:"一叶知秋，一绿春来，一热夏至，一冷冬眠"
    }
    ListElement{
        img:"qrc:/images/4.png"
        name:"寒山居士"
        space:"qrc:/images/callme.png"
        limit:"qrc:/images/callme.png"
        contents:"一叶知秋，一绿春来，一热夏至，一冷冬眠"
    }
}
